### ISSUE TITLE
$lang strings sollten escaped werden

### ISSUE THREAD

**Issue by JN-Jones** [SvePu/MinifyHTML#1]
`"title"        =>  $lang->minifyhtml_settings_title,`
Da Sprachstrings (gerade im englischen) auch Zeichen wie `'` beinhalten können, sollten diese escaped werden:
`"title"        =>  $db->escape_string($lang->minifyhtml_settings_title),`

**Comment by SvePu** [comment]
Danke, werde es gleich ändern.
