### ISSUE TITLE
Bei deinstallation write_query oder delete_query nutzen

### ISSUE THREAD

**Issue by JN-Jones** [SvePu/MinifyHTML#2]
Während der Deinstallation:
`$db->query("DELETE FROM ".TABLE_PREFIX."settinggroups WHERE name='minifyhtml_settings'");`

Dadurch wird zum einen das Master/Slave system von MyBB verletzt (änderungen an der Datenbank sollten `write_query` nutzen) und gleichzeitig können Fehler unter PgSQL/SQLite auftreten. Besser wäre:
`$db->delete_query("settinggroups", "name='minifyhtml_settings'");`

**Comment by SvePu** [comment]
Danke, werde es gleich abändern.
